# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbe31278f3b82eeb271a8ed9d351d9a8060e33714779341b9c910f2b01e5b02779690d6ea1993f85e0b19887cffab80411a999b01f2137284490d3e17f12d6d2

test:
  secret_key_base: 0128c0df0b7319e9ba36ae67db31e7f34329ef7b8cac6ffd6d7177252e8f048b6bdaa95443e1f037b69f408e3e47bbd3ae2c0b493df733af4d0e48e3e98fecbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
